import { SLUG_TO_MODULE, ROUTE_SLUGS } from './route-slugs'
import type { Language } from '@/shared/types/languages'
import type { RouteModule } from './route-slugs'

const MODULE_LABELS: Record<RouteModule, Record<Language, string>> = {
  forbidden: {
    es: 'No autorizado',
    en: 'Unauthorized',
    de: 'Nicht autorisiert',
    fr: 'Accès interdit',
    pt: 'Não autorizado',
    it: 'Non autorizzato',
    ja: '未認可',
    ko: '미승인',
    zh: '未授权',
    ru: 'Не авторизован',
  },
  notFound: {
    es: 'No encontrada',
    en: 'Not Found',
    de: 'Nicht gefunden',
    fr: 'Introuvable',
    pt: 'Não encontrada',
    it: 'Non trovata',
    ja: '見つかりません',
    ko: '찾을 수 없음',
    zh: '未找到',
    ru: 'Не найдено',
  },
  users: {
    es: 'Usuarios',
    en: 'Users',
    de: 'Benutzer',
    fr: 'Utilisateurs',
    pt: 'Utilizadores',
    it: 'Utenti',
    ja: 'ユーザー',
    ko: '사용자',
    zh: '用户',
    ru: 'Пользователи',
  },
  userCreate: {
    es: 'Nuevo',
    en: 'New',
    de: 'Neu',
    fr: 'Nouveau',
    pt: 'Novo',
    it: 'Nuovo',
    ja: '新規',
    ko: '새로',
    zh: '新建',
    ru: 'Новый',
  },
  userEdit: {
    es: 'Editar',
    en: 'Edit',
    de: 'Bearbeiten',
    fr: 'Modifier',
    pt: 'Alterar',
    it: 'Modifica',
    ja: '編集',
    ko: '편집',
    zh: '编辑',
    ru: 'Редактировать',
  },
  userGroups: {
    es: 'Grupos',
    en: 'Groups',
    de: 'Gruppen',
    fr: 'Groupes',
    pt: 'Grupos',
    it: 'Gruppi',
    ja: 'グループ',
    ko: '그룹',
    zh: '群组',
    ru: 'Группы',
  },
  userGroupCreate: {
    es: 'Nuevo',
    en: 'New',
    de: 'Neu',
    fr: 'Nouveau',
    pt: 'Novo',
    it: 'Nuovo',
    ja: '新規',
    ko: '새로',
    zh: '新建',
    ru: 'Новый',
  },
  userGroupEdit: {
    es: 'Editar',
    en: 'Edit',
    de: 'Bearbeiten',
    fr: 'Modifier',
    pt: 'Alterar',
    it: 'Modifica',
    ja: '編集',
    ko: '편집',
    zh: '编辑',
    ru: 'Редактировать',
  },
  userGroupUsers: {
    es: 'Miembros',
    en: 'Members',
    de: 'Mitglieder',
    fr: 'Membres',
    pt: 'Membros',
    it: 'Membri',
    ja: 'メンバー',
    ko: '구성원',
    zh: '成员',
    ru: 'Участники',
  },
  userTrash: {
    es: 'Papelera',
    en: 'Trash',
    de: 'Papierkorb',
    fr: 'Corbeille',
    pt: 'Lixeira',
    it: 'Cestino',
    ja: 'ゴミ箱',
    ko: '휴지통',
    zh: '回收站',
    ru: 'Корзина',
  },
  userGroupTrash: {
    es: 'Papelera',
    en: 'Trash',
    de: 'Papierkorb',
    fr: 'Corbeille',
    pt: 'Lixeira',
    it: 'Cestino',
    ja: 'ゴミ箱',
    ko: '휴지통',
    zh: '回收站',
    ru: 'Корзина',
  },
  clients: {
    es: 'Clientes',
    en: 'Clients',
    de: 'Kunden',
    fr: 'Clients',
    pt: 'Clientes',
    it: 'Clienti',
    ja: 'クライアント',
    ko: '클라이언트',
    zh: '客户',
    ru: 'Клиенты',
  },
  services: {
    es: 'Servicios',
    en: 'Services',
    de: 'Dienste',
    fr: 'Services',
    pt: 'Serviços',
    it: 'Servizi',
    ja: 'サービス',
    ko: '서비스',
    zh: '服务',
    ru: 'Услуги',
  },
  portfolio: {
    es: 'Portafolio',
    en: 'Portfolio',
    de: 'Portfolio',
    fr: 'Portfolio',
    pt: 'Portfólio',
    it: 'Portfolio',
    ja: 'ポートフォリオ',
    ko: '포트폴리오',
    zh: '作品集',
    ru: 'Портфолио',
  },
  pages: {
    es: 'Páginas',
    en: 'Pages',
    de: 'Seiten',
    fr: 'Pages',
    pt: 'Páginas',
    it: 'Pagine',
    ja: 'ページ',
    ko: '페이지',
    zh: '页面',
    ru: 'Страницы',
  },
  collaborators: {
    es: 'Colaboradores',
    en: 'Collaborators',
    de: 'Mitarbeiter',
    fr: 'Collaborateurs',
    pt: 'Colaboradores',
    it: 'Collaboratori',
    ja: 'コラボレーター',
    ko: '협력자',
    zh: '合作者',
    ru: 'Сотрудники',
  },
  subscribers: {
    es: 'Suscriptores',
    en: 'Subscribers',
    de: 'Abonnenten',
    fr: 'Abonnés',
    pt: 'Assinantes',
    it: 'Iscritti',
    ja: '購読者',
    ko: '구독자',
    zh: '订阅者',
    ru: 'Подписчики',
  },
  auditLogs: {
    es: 'Auditoría',
    en: 'Audit Logs',
    de: 'Audit-Logs',
    fr: "Journaux d'audit",
    pt: 'Auditoria',
    it: 'Registri di audit',
    ja: '監査ログ',
    ko: '감사 로그',
    zh: '审计日志',
    ru: 'Логи аудита',
  },
  appSettings: {
    es: 'Configuración',
    en: 'App Settings',
    de: 'Einstellungen',
    fr: 'Paramètres',
    pt: 'Configurações',
    it: 'Impostazioni',
    ja: 'アプリ設定',
    ko: '설정',
    zh: '应用设置',
    ru: 'Настройки',
  },
  profile: {
    es: 'Perfil',
    en: 'Profile',
    de: 'Profil',
    fr: 'Profil',
    pt: 'Perfil',
    it: 'Profilo',
    ja: 'プロフィール',
    ko: '프로필',
    zh: '个人资料',
    ru: 'Профиль',
  },
}

const HOME_LABELS: Record<Language, string> = {
  es: 'Inicio',
  en: 'Home',
  de: 'Start',
  fr: 'Accueil',
  pt: 'Início',
  it: 'Inizio',
  ja: 'ホーム',
  ko: '홈',
  zh: '首页',
  ru: 'Главная',
}

export function getSegmentLabel(slug: string, uiLang: Language): string {
  const module = SLUG_TO_MODULE[slug]
  if (module) return MODULE_LABELS[module][uiLang]
  return slug
}

export function getHomeLabel(lang: Language): string {
  return HOME_LABELS[lang]
}

// Kept for backwards-compat; prefer getSegmentLabel for new code
export const SEGMENT_LABELS: Readonly<Record<string, string>> =
  Object.fromEntries(
    (Object.keys(ROUTE_SLUGS) as RouteModule[]).flatMap((module) =>
      Object.values(ROUTE_SLUGS[module]).map((slug) => [
        slug,
        MODULE_LABELS[module].es,
      ])
    )
  )
