import type { Language } from '@/shared/types/languages'

export const ROUTE_SLUGS = {
  forbidden: {
    es: 'no-autorizado',
    en: 'unauthorized',
    de: 'nicht-autorisiert',
    fr: 'acces-interdit',
    pt: 'nao-autorizado',
    it: 'non-autorizzato',
    ja: 'mi-ninka',
    ko: 'mi-seungni',
    zh: 'wei-shouquan',
    ru: 'ne-avtorizovan',
  },
  notFound: {
    es: 'no-encontrada',
    en: 'not-found',
    de: 'nicht-gefunden',
    fr: 'introuvable',
    pt: 'nao-encontrada',
    it: 'non-trovata',
    ja: 'mitsuke-nai',
    ko: 'mot-chateum',
    zh: 'wei-zhaodao',
    ru: 'ne-naydeno',
  },
  users: {
    es: 'usuarios',
    en: 'users',
    de: 'benutzer',
    fr: 'utilisateurs',
    pt: 'utilizadores',
    it: 'utenti',
    ja: 'yuzaa',
    ko: 'sayongja',
    zh: 'yonghu',
    ru: 'polzovateli',
  },
  userCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  userEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  userGroups: {
    es: 'grupos',
    en: 'groups',
    de: 'gruppen',
    fr: 'groupes',
    pt: 'agrupamentos',
    it: 'gruppi',
    ja: 'guruupu',
    ko: 'geurup',
    zh: 'zuqun',
    ru: 'gruppy',
  },
  userGroupCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  userGroupEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  userGroupUsers: {
    es: 'miembros',
    en: 'members',
    de: 'mitglieder',
    fr: 'membres',
    pt: 'membros',
    it: 'membri',
    ja: 'menbaa',
    ko: 'guseongwon',
    zh: 'chengyuan',
    ru: 'uchastniki',
  },
  userTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  userGroupTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  clients: {
    es: 'clientes',
    en: 'clients',
    de: 'kunden',
    fr: 'clients',
    pt: 'clientes',
    it: 'clienti',
    ja: 'kuraianto',
    ko: 'geollaianteu',
    zh: 'kehu',
    ru: 'klienty',
  },
  clientCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  clientEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  clientTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  services: {
    es: 'servicios',
    en: 'services',
    de: 'dienste',
    fr: 'services',
    pt: 'servicos',
    it: 'servizi',
    ja: 'saabisu',
    ko: 'seobiseu',
    zh: 'fuwu',
    ru: 'uslugi',
  },
  serviceCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  serviceEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  serviceTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  portfolio: {
    es: 'portafolio',
    en: 'portfolio',
    de: 'portfolio',
    fr: 'portfolio',
    pt: 'portfolio',
    it: 'portfolio',
    ja: 'pootoforio',
    ko: 'poteupolio',
    zh: 'zuopinjixu',
    ru: 'portfolio',
  },
  portfolioCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  portfolioEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  portfolioTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  pages: {
    es: 'paginas',
    en: 'pages',
    de: 'seiten',
    fr: 'pages',
    pt: 'paginas',
    it: 'pagine',
    ja: 'peeji',
    ko: 'peiji',
    zh: 'yemian',
    ru: 'stranicy',
  },
  pageCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  pageEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  pageBuilder: {
    es: 'construir',
    en: 'builder',
    de: 'baukasten',
    fr: 'construire',
    pt: 'construtor',
    it: 'costruttore',
    ja: 'biruda',
    ko: 'bildeo',
    zh: 'goujian',
    ru: 'konstruktor',
  },
  pageTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  collaborators: {
    es: 'colaboradores',
    en: 'collaborators',
    de: 'mitarbeiter',
    fr: 'collaborateurs',
    pt: 'colaboradores',
    it: 'collaboratori',
    ja: 'kyodokusha',
    ko: 'hyeobyeokja',
    zh: 'hezuozhe',
    ru: 'soavtory',
  },
  collaboratorCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  collaboratorEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  collaboratorTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  categories: {
    es: 'categorias',
    en: 'categories',
    de: 'kategorien',
    fr: 'categories',
    pt: 'categorias',
    it: 'categorie',
    ja: 'kategori',
    ko: 'kategori',
    zh: 'fenlei',
    ru: 'kategorii',
  },
  categoryCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  categoryEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  categoryTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  tags: {
    es: 'etiquetas',
    en: 'tags',
    de: 'schlagworte',
    fr: 'mots-cles',
    pt: 'etiquetas',
    it: 'tag',
    ja: 'tagu',
    ko: 'taegeu',
    zh: 'biaoqian',
    ru: 'tegi',
  },
  tagCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  tagEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  tagTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  media: {
    es: 'multimedia',
    en: 'media',
    de: 'medien',
    fr: 'multimedia',
    pt: 'multimedia',
    it: 'multimedia',
    ja: 'media',
    ko: 'midieo',
    zh: 'meiti',
    ru: 'media',
  },
  mediaTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  siteConfig: {
    es: 'sitio-web',
    en: 'website',
    de: 'webseite',
    fr: 'site-web',
    pt: 'site',
    it: 'sito-web',
    ja: 'saito',
    ko: 'saiteu',
    zh: 'wangzhan',
    ru: 'sait',
  },
  subscribers: {
    es: 'suscriptores',
    en: 'subscribers',
    de: 'abonnenten',
    fr: 'abonnes',
    pt: 'assinantes',
    it: 'iscritti',
    ja: 'dokuusha',
    ko: 'gudokja',
    zh: 'dingyuezhe',
    ru: 'podpischiki',
  },
  subscriberCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  subscriberEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  subscriberTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  forms: {
    es: 'formularios',
    en: 'forms',
    de: 'formulare',
    fr: 'formulaires',
    pt: 'formularios',
    it: 'moduli',
    ja: 'fomu',
    ko: 'yangsik',
    zh: 'biaodan',
    ru: 'formy',
  },
  formCreate: {
    es: 'nuevo',
    en: 'new',
    de: 'neu',
    fr: 'nouveau',
    pt: 'novo',
    it: 'nuovo',
    ja: 'atarashii',
    ko: 'sae',
    zh: 'xin',
    ru: 'novyy',
  },
  formEdit: {
    es: 'editar',
    en: 'edit',
    de: 'bearbeiten',
    fr: 'modifier',
    pt: 'alterar',
    it: 'modifica',
    ja: 'henshu',
    ko: 'pyeonjip',
    zh: 'bianji',
    ru: 'redakt',
  },
  formTrash: {
    es: 'papelera',
    en: 'trash',
    de: 'papierkorb',
    fr: 'corbeille',
    pt: 'lixeira',
    it: 'cestino',
    ja: 'gomibako',
    ko: 'hujiji',
    zh: 'lajitong',
    ru: 'korzina',
  },
  formSubmissions: {
    es: 'respuestas',
    en: 'submissions',
    de: 'einsendungen',
    fr: 'reponses',
    pt: 'respostas',
    it: 'risposte',
    ja: 'soshin',
    ko: 'eungdab',
    zh: 'tijiao',
    ru: 'zayavki',
  },
  auditLogs: {
    es: 'auditoria',
    en: 'audit-logs',
    de: 'audit-logs',
    fr: 'journaux-audit',
    pt: 'registros-auditoria',
    it: 'registri-audit',
    ja: 'kansa-rogu',
    ko: 'gamsa-rogeu',
    zh: 'shenji-rizhi',
    ru: 'zhurnaly-audita',
  },
  appSettings: {
    es: 'configuracion',
    en: 'settings',
    de: 'einstellungen',
    fr: 'parametres',
    pt: 'configuracoes',
    it: 'impostazioni',
    ja: 'settei',
    ko: 'seoljeong',
    zh: 'shezhi',
    ru: 'nastroyki',
  },
  profile: {
    es: 'perfil',
    en: 'profile',
    de: 'profil',
    fr: 'profil',
    pt: 'perfil',
    it: 'profilo',
    ja: 'purofiiru',
    ko: 'peoropil',
    zh: 'gerenziliao',
    ru: 'profil',
  },
} as const satisfies Record<string, Record<Language, string>>

export type RouteModule = keyof typeof ROUTE_SLUGS

// Reverse lookup: any slug (across all languages) -> module key
export const SLUG_TO_MODULE: Readonly<Record<string, RouteModule>> =
  Object.fromEntries(
    (
      Object.entries(ROUTE_SLUGS) as [RouteModule, Record<Language, string>][]
    ).flatMap(([module, langs]) =>
      Object.values(langs).map((slug) => [slug, module])
    )
  )

export function translatePath(path: string, newLang: Language): string {
  const segments = path.split('/').filter(Boolean)
  if (segments.length === 0) return `/${newLang}`

  // segments[0] is the current lang -- replace it
  const rest = segments.slice(1)

  const translatedRest = rest.map((segment) => {
    const module = SLUG_TO_MODULE[segment]
    if (module) return ROUTE_SLUGS[module][newLang]
    return segment // IDs and unknown segments pass through unchanged
  })

  const tail = translatedRest.length ? `/${translatedRest.join('/')}` : ''
  return `/${newLang}${tail}`
}
